//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Obsidian_ToolBox_Update_Properties_Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Obsidian_ToolBox_Update_Properties_Resources() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obsidian_ToolBox_Update.Properties.Resources", typeof(Obsidian_ToolBox_Update_Properties_Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   重写当前线程的 CurrentUICulture 属性，对
    ///   使用此强类型资源类的所有资源查找执行重写。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap add_32x32 {
        get {
            object obj = ResourceManager.GetObject("add_32x32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage electronics_desktopmac {
        get {
            object obj = ResourceManager.GetObject("electronics_desktopmac", resourceCulture);
            return ((DevExpress.Utils.Svg.SvgImage)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap kisspng_call_of_duty_modern_warfare_3_delta_force_united_5af9c6fe30bf93_4497314715263188461997 {
        get {
            object obj = ResourceManager.GetObject("kisspng-call-of-duty-modern-warfare-3-delta-force-united-5af9c6fe30bf93.449731471" +
                    "5263188461997", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap kisspng_call_of_duty_modern_warfare_3_delta_force_united_5af9c6fe30bf93_4497314715263188461997_jpg {
        get {
            object obj = ResourceManager.GetObject("kisspng-call-of-duty-modern-warfare-3-delta-force-united-5af9c6fe30bf93.449731471" +
                    "5263188461997.jpg", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap Screenshot_1 {
        get {
            object obj = ResourceManager.GetObject("Screenshot_1", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
